# launcher name & url
launcher_name=ZyNova
launcher_app_name=ZyNova Launcher
launcher_short_name=ZyNova
url_home=https://github.com/ZalithLauncher/ZalithLauncher2

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
#curseforge_api_key=xxx

# default key, please add it yourself.
default_store_password=vh#nn%N(#eNjwfA78-77s6&f-cdd(@-7eana-e%!nhj%))!@c
default_key_password=sfv72ghSSNQaadf99-Q69!2

# launcher version
launcher_version_code=200036
launcher_version_name=2.5